<h1>Test <?= $controllerRoute ?> </h1>

<form method="post" enctype="multipart/form-data">
    <input type="text" name="name" value="">
    <input type="checkbox" name="days[]" value="Segunda">
    <input type="checkbox" name="days[]" value="Terça">
    <input type="checkbox" name="days[]" value="Quarta">
    <input type="file" name="image" value="">
    <button type="submit">Enviar</button>
</form>